### ISSUE TITLE
Digrafy

### ISSUE THREAD

**Issue by NarQiu** [embchnk/Graphs#3]
Dodajmy **pole prywatne**, które będzie informować o typie grafu. Inne typy pociągają za sobą inny sposób szukania błędów w reprezentacji, bo coś, co było błędem w grafie prostym, jest normą/podstawą działania digrafu.
Najlepiej niech to będzie **int**.
0 -> graf prosty
1 -> digraf
a potem zapewne jeszcze inne rzeczy, pewnie krawędź wychodząca i wracająca do jednego wierzchołka.
No i pewnie jeszcze const funkcja, która zwraca const int się przyda.

**Comment by NarQiu** [comment]
Jako że napisałem pierwszy i można to zunifikować, to niech funkcje nazywają się
bool setGraphType(int);
const int getGraphType() const { return jak_wam_sie_podoba_nazwa_ja_dalem gType }

**Comment by piotrcholody** [comment]
Dlaczego pierw nie skończymy grafów prostych zanim zaczniemy lecieć w inne przypadki? No i jeśli chcemy robić tego typu metody to nie lepiej zrobić jakąś główną klasę abstrakcyjną po której będziemy to dziedziczyć, a tak tylko burdel się zrobi.

**Comment by NarQiu** [comment]
No ja nadal czekam na metodę zwracającą ilość wierzchołków i krawędzi.
Więc miałem czas to pisałem dalej.

**Comment by piotrcholody** [comment]
Następnym razem się upomnij, bo nie napisałeś mi o tym ani razu, tylko wspomniałeś na zajęciach. Myślałem, że wystarczy ci ref na macierz, bo masz tam wszystkie potrzebne dane.

**Comment by NarQiu** [comment]
Skoro do digrafów robicie nowe klasy, to pomysł staje się bez sensu.
