### ISSUE TITLE
qt gui

### ISSUE THREAD

**Issue by piotrcholody** [embchnk/Graphs#5]
Do narysowania tego wszystkiego będę potrzebował:
- metody do zwracania ilości wierzchołków "getN"
- metody do zwracania ilości krawędzi "getL"
- metody do zwracania macierzy "getMatrix"
- przejście z ConnectionMatrix do IncidenceMatrix.

Metody już pewnie macie ale zależy mi żeby wszyscy (sam też muszę zmienić) mieli te same nazwy, bo często się ich używa.
Na razie to wszystko co mi potrzebne.

**Comment by embe221ed** [comment]
Ogólnie mogę ogarnąć dwa pierwsze podpunkty, ale co rozumiesz jako zwracanie macierzy w przypadku listy sąsiedztwa?

**Comment by piotrcholody** [comment]
Chodzi mi o wektor po prostu, Czubi robił tablicą to niech zwraca tablicę.
