### ISSUE TITLE
zestaw 1

### ISSUE THREAD

**Issue by piotrcholody** [embchnk/Graphs#8]
GUI do pierwszego zestawu skończone. Wrzuciłem je do oddzielnego brancha. Problem jest taki, że wasze pliki nagłówkowe mogą być tam niezaktualizowane (Czubali na pewno, reszta mogą być ok), bo nie pullowalem ich za każdym razem bo nie pracowałem w vs. Zadanie jest takie żebyście pobrali całość, nadpisali swoimi nagłówkowymi i wszystko w teorii powinno działać. Jeśli zadziała to będzie można przerzucić do mastera z aktualnymi nagłówkowymi.

**Comment by embe221ed** [comment]
Albo po prostu przerzucić do mastera wszystko oprócz plików z naszymi reprezentacjami
